### PR TITLE
upgrade publicsuffix to v2

### PR DESCRIPTION
**Pull request by rushmorem**

### CODE REVIEW

**Comment by rushmorem** [comment]
@pfernie I have marked this pull request RFC because I'm not sure if a static list like `psl` will be able to accommodate all the users of this crate's use cases. I would imagine some might want a list they can update dynamically at runtime or even use their own list different from the one provided by https://publicsuffix.org.

**Comment by rushmorem** [comment]
Thanks for the feedback. I'm planning to rewrite `publicsuffix` to make it faster and leaner. I have marked this pull request as work in progress for now. I will get back to it once `publicsuffix` v2 is out so we won't need to do another breaking change then.

**Comment by rushmorem** [comment]
Reopening. GitHub automatically closed it when I reset my branch to start afresh :(

**Comment by rushmorem** [comment]
Reopening. GitHub automatically closed it when I reset my branch to start afresh :(

**Comment by rushmorem** [comment]
Reopening. GitHub automatically closed it when I reset my branch to start afresh :(

**Comment by rushmorem** [comment]
@pfernie This PR is now ready for review. Version 2 of the `psl` and `publicsuffix`  crates is now out. This PR allows `cookie_store` to abstract over public suffix implementations by accepting any implementation of [the psl_types::List trait](https://docs.rs/psl-types/2/psl_types/trait.List.html).

**Comment by pfernie** [comment]
Thanks for the updated PR; I would like to consider whether we could avoid introducing the generic parameter on `CookieStore` by instead resorting to `dyn`. Much as the `CookieStore` trait is itself handled within [`reqwest::Client`](https://github.com/seanmonstar/reqwest/blob/c6eb2c4fcbc3934b119772e0997d91671ff68dc7/src/async_impl/client.rs#L106). In cases where users aren't utilizing `with_suffix_list`, it is conceptually a little awkward to then be parameterizing the `CookieStore` over a particular implementation.

**Comment by rushmorem** [comment]
@pfernie I did consider using a trait object. I went with the generic parameter because it's more flexible. One use case I wanted to support was passing a non-`'static` reference to `with_suffix_list` so users wouldn't have to clone the list if they are using it for something else and they don't need to use something like `lazy_static`.

> In cases where users aren't utilizing with_suffix_list, it is conceptually a little awkward to then be parameterizing the CookieStore over a particular implementation.

You are right. That's been bugging me too. I have been meaning to leave a comment about this but you beat me to it. I've even considered just upgrading to `publicsuffix` v2 and calling it a day, now that it's almost as fast as `psl` and has very few dependencies. The problem I have with the current implementation though is moving the entire list into `CookieStore` which would require cloning for those who use the list for other purposes. That doubles the memory usage and it makes updating the list more involved. Users would have to update the list and then update the copy in `CookieStore`.

Having said that, I agree with you. A trait object might be a good compromise after weighing the tradeoffs. Users can still use `lazy_static` if they want to share the list and update it from one place. `psl_types::List` is not object safe though so I'm thinking of defining an extension trait in the `cookie_store` module. Say

```rust
pub trait PublicSuffixList {
    fn suffix<'a>(&self, name: &'a str) -> Option<psl_types::Suffix<'a>>;
}
```

Would that be acceptable to you?

**Comment by pfernie** [comment]
Can you describe a little more some alternative use cases you are considering? For my usage, it is typically in conjunction with `reqwest`, and as such any shared access I would anticipate needing to be `Send + Sync`.

The actual interaction b/w `CookieStore` and the suffix list is minimal; I am wondering if we could instead store a closure `Fn(&[u8]) -> bool` which could be passed the cookie domain. I've worked up a sample of what I mean in [this](https://github.com/pfernie/cookie_store/tree/alt-psl-example) branch.

So `CookieDomain::is_public_suffix` would become something like:
```
    pub fn is_public_suffix<F: Fn(&[u8]) -> bool>(&self, is_publicsuffix: F) -> bool {
        if let Some(domain) = self.as_cow().as_ref().map(|d| d.as_bytes()) {
            is_publicsuffix(domain)
        } else {
            false
        }
    }
```

`CookieStore::public_suffix_list` would be redefined (this field and the `with_suffix_list` method should probably be renamed, too):
```
    public_suffix_list: Option<Box<dyn (for<'r> Fn(&'r [u8]) -> bool) + Send + Sync>>,
```

And the signature of `with_suffix_list` would change:
```
    pub fn with_suffix_list<F: (Fn(&[u8]) -> bool) + Send + Sync + 'static>(
        self,
        psl: F,
    ) -> CookieStore {
```

Users would have a fair bit of freedom, and could use a shared list for example:
```
        use psl_types::List;
        let psl: publicsuffix::List = r#"// ===BEGIN ICANN DOMAINS===

// ac : https://en.wikipedia.org/wiki/.ac
ac
com.ac
edu.ac
gov.ac
net.ac
mil.ac
org.ac"#
            .parse()
            .unwrap();
        let psl = std::sync::Arc::new(std::sync::RwLock::new(psl));
        let psl = {
            let psl = psl.clone();
            let psl = move |domain: &[u8]| {
                let psl = psl.read().unwrap();
                psl.suffix(domain)
                    // Only consider suffixes explicitly listed in the public suffix list
                    // to avoid issues like https://github.com/curl/curl/issues/658
                    .filter(psl_types::Suffix::is_known)
                    .filter(|suffix| suffix == &domain)
                    .is_some()
            };
            psl
        };

        let mut store = CookieStore::default().with_suffix_list(psl);
```

Which admittedly doesn't exactly match your described case of a non-`'static` reference, but (again, for me), this (using something behind `Arc`) would be typical usage if using the store with `reqwest` or similar.

**Comment by rushmorem** [comment]
> Can you describe a little more some alternative use cases you are considering?

My use cases were theoretical. Judging by how users might want to use the public suffix list, I assumed you had such users here. Now that you have clarified what you use the library for, I don't think there is any need to complicate your API unnecessarily (YAGNI? :)). So I have just upgraded to v2 instead. Sorry for the noise :(

> I am wondering if we could instead store a closure Fn(&[u8]) -> bool which could be passed the cookie domain. I've worked up a sample of what I mean in this branch.

That implementation was even more general, which I like. However, it's general to the point of losing its important types opening up potential for a user to misuse that API, which can lead to bugs. I think just upgrading `publicsuffix` is enough for now. We can revisit this decision later if a user requests this particular feature.

**Comment by pfernie** [comment]
Thanks for your work on this; I've merged the "just v2" version now. I'd be happy to entertain the more general patch in the future if a use case arises!

**Pull request merged**
